# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      APPN: VHWSL
      NCBEXEN: $APPN-$VER-Sslf_Contained.tar.gz
      git_hash: $(git rev-parse --short "$GITHUB_SHA")
      CBEXEN: $APPN-$VER.tar.gz

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo $git_hash

      # Runs a set of commands using the runners shell
      - name: Building self contained release
        env:
           CBEXEN: $APPN-$VER.tar.gz
        run: ./Build --cb $APPN $git_hash
          
      - name: 'Upload Self Contained Artifact'
        uses: actions/upload-artifact@v2
        env:
          VER: git rev-parse --short <commit_hash>
          NCBEXEN: $APPN-v2.0.0-Sslf_Contained.tar.gz
        with:
          name: VHWSL-'$git_hash'-Self_Contained
          path: "/home/runner/work/VHWSL/VHWSL/bin/release/netcoreapp3.1/ubuntu.20.04-x64/publish/VHWSL-'$git_hash'-Self_Contained.tar.gz"
          retention-days: 10
          
      - name: Building Standard Release
        env:
           VER: $(git rev-parse --short <commit_hash>)
           CBEXEN: VHWSL-v2.0.0.tar.gz
        run: ./Build --ncb $APPN $git_hash
          
      - name: 'Upload standard Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: VHWSL-'$git_hash'
          path: "/home/runner/work/VHWSL/VHWSL/bin/release/netcoreapp3.1/ubuntu.20.04-x64/VHWSL-'$git_hash'.tar.gz"
          retention-days: 10
