# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      VER: v2.0.0
      APPN: VHWSL
      NCBEXEN: $APPN-$VER-Sslf_Contained.tar.gz
      CBEXEN: $APPN-$VER.tar.gz

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          ./Build --ncb $APPN $VER
          ./Build --cb $APPN $VER
          
      - name: 'Upload Self Contained Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: "VHWSL-$VER-Self_Contained.tar.gz"
          path: "/home/runner/work/VHWSL/VHWSL/bin/release/netcoreapp3.1/ubuntu.20.04-x64/publish/VHWSL-$VER-Self_Contained.tar.gz"
          retention-days: 10

      - name: 'Upload standard Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: "VHWSL-$VER.tar.gz"
          path: "/home/runner/work/VHWSL/VHWSL/bin/release/netcoreapp3.1/ubuntu.20.04-x64/VHWSL-$VER.tar.gz"
          retention-days: 10
